## Basic Information and Life History
*Note: Prior to the identification of sunset rockfish as a separate species [-@Hyde2008b], historical studies of “vermilion” rockfish, particularly those conducted south of Point Conception (\PtC), California, could have included a mixture of both species. Also, many current studies and data sets (e.g., landing statistics) do not distinguish between the species. In this document, we refer simply to “vermilion rockfish” when no species-specific information is available.*



Vermilion rockfish (*Sebastes miniatus*) range from Prince William Sound, Alaska, to central Baja California at 
depths of 6 m to 436 m [@Love2002]. However, they are most commonly found from central Oregon
to Punta Baja, Mexico [@Hyde2009] at depths of 50 m to 150 m [@Hyde2009].  Hyde and Vetter 
[-@Hyde2009] describe vermilion rockfish as residents of shallower depths (<100 m) than their sibling species,
sunset rockfish (*Sebastes crocotulus*). Adult fish tend to cluster on high relief rocky outcrops [@Love2002] 
and kelp forests [@Hyde2009]. North of Point Conception, California, some adults are shallower, 
living in caves and cracks [@Love2002]. Vermilion rockfish have shown high site fidelity 
[@Hannah2011 (only tagged 1 vermilion); @Lea1999], and low to average larval dispersal 
distance [@Hyde2009]. Lowe et al. [-@Lowe2009] suggested that vermilion rockfish 
have a lower site fidelity than previously believed, but acknowledged that their
observations of movements to different depths may have been due to differences in depth distribution between the species. 
Vermilion rockfish have been aged to over 80 years, but few fish have been aged above 60 years, with females growing larger than their male counterparts. 50% of females are mature at 5 years and about 
37 cm, with males probably maturing at shorter lengths than females [@Love2002].

Vermilion rockfish are viviparous, and females produce an estimated 63,000 to 2,600,000 eggs per brood, with larger fish releasing a substantially larger number of larvae. 
In southern California, vermilion rockfish larvae are released between July and March. 
In central and northern California, this release occurs in September, December, and 
April-June [@Love2002].  Larval release in fall and winter is not common among other 
rockfish species. Hyde and Vetter [-@Hyde2009] suggest that low larval dispersal may 
be due to weak poleward flow of nearshore waters corresponding with peak vermilion larval release. 

Young-of-the-year vermilion rockfish settle out of the water column during two primary recruitment 
periods per year, first from February to April and a second from August to October, 
and settlement has been observed in May off southern California [@Love2002]. Larvae 
measure about 4.3 mm. Young-of-the-year vermilion and sunset rockfish are both mottled 
brown with areas of black, and older juveniles turn a mottled orange or red color [@Love2012a]. 
Juvenile fish are found individually from 6 m to 36 m, living near sand and structures. 
After two months, juveniles travel deeper and live on low relief rocky outcrops and 
other structures [@Love2002].

Adult vermilion rockfish predominantly eat smaller fish, though sometimes they pursue 
euphausiids and other various macroplankton [@Phillips1964]. Love [-@Love2002] noted 
their diet includes octopuses, salps, shrimps, and pelagic red crabs. 


*Population Structure and Multi-species Assessment Considerations*

This assessment represents the aggregate population dynamics of the cryptic species pair vermilion rockfish 
and sunset rockfish.
Hyde [-@Hyde2007] examined seven mitochondrial and two nuclear genes, which upon analysis suggested 
three species within the subgenus *Rosicola*. Hyde et al. [-@Hyde2008b] described sunset rockfish as a distinct species noting depth separation 
of the adult populations of the two species using nine microsatellite loci. 
Adult sunset rockfish are mainly distributed at depths 
greater than 50 fm (100 m) and are predominantly located south of Point Conception (\PtC). 
Hyde [@Hyde2009] and Budrick [@Budrick2016]  identified species using mtDNA assays and microsatellite loci, 
respectively.  The mtDNA analyses proved to be subject to errors in species identification due to introgression resulting from mating between the two species post-divergence.
Additional population clusters of vermilion were found north of Point Conception, but neither 
study detected population structure between Half Moon Bay, California and Brookings, 
Oregon [@Hyde2009; @Budrick2016].

Vermilion and sunset rockfishes are morphologically very similar, with color being 
the most commonly 
cited differentiating feature. Hyde [-@Hyde2009] noted differences in three of six morphological 
parameters examined, but none of them can readily be used for field identification.

In all historical and current recreational and commercial catches, sunset and 
vermilion rockfish are both recorded as vermilion rockfish.  Future studies, 
such as the one described below will provide data needed to compare biological 
parameters between the two species as well as habitats.

_Ongoing Population Structure Research (Provided by John Harms, NWFSC)_

A group of researchers from the NWFSC and SWFSC is collaborating on a project to 
genotype tissue specimens collected from the vermilion and sunset rockfish cryptic 
pair captured during the West Coast Groundfish Bottom Trawl Survey and the Southern 
CA Shelf Rockfish Hook and Line Survey for the years 2004 - 2019.  Funding for this 
project was obtained through the Saltonstall-Kennedy program for FY 2020 through a 
proposal led by representatives from Pacific States Marine Fisheries Commission and 
the commercial passenger fishing vessel industry in southern California.  

After combining with specimens obtained through other collection efforts along 
the West Coast, approximately 25,000 tissue specimens will be analyzed.  Some 
earlier efforts to separate this cryptic pair to species used mitochondrial DNA 
(mtDNA) markers.  However, due to a one-way mitochondrial introgression from 
the vermilion genome into the sunset genome, a portion of the sunset rockfish 
population contains mitochondrial DNA sequences consistent with vermilion rockfish 
resulting in incorrect species assignments for these introgressed individuals 
during the prior research project.  The current research has identified a robust 
suite of genetic markers within the nuclear genomes of the two species that 
definitively separates vermilion and sunset rockfish (including  introgressed 
sunset rockfish), canary rockfish, first generation vermilion-sunset hybrids, 
and identifies emerging patterns of intraspecific stock structure within the 
two sister species.

Once the collected specimens have been genotyped, any species-specific differences 
in spatial and depth distribution, size composition, weight-length relationships, 
and other biological characteristics will be identified.  Using previously 
collected otoliths and ovaries, the demographics of the two species including 
age and growth and reproductive biology parameters such as length and age at 
50% maturity and the prevalence of skip spawning will be explored and compared. 
These new genotyping results will be combined with data from the prior mtDNA 
work to  evaluate whether introgressed sunset rockfish represent a biologically
intermediate subform of the species complex.  The effort also proposes to develop 
and test the efficacy of models to predict the relative proportion of the two 
species based upon explanatory variables including latitude, depth, species of 
co-occurrence, oceanographic parameters, habitat descriptors and/or other 
information.  The anticipated completion of the genotyping of all specimens 
is approximately December 2021 with provision of final results by the end of FY 2022.

This research is aimed at providing information to support the successful stock
assessment of this commercially and recreationally valuable cryptic species pair 
and is responsive to any data gaps identified by the assessment community.  If 
successful, this research, conducted in close communication with stock assessors, 
may also assist the PFMC in establishing best practices for the assessment and 
management of cryptic species complexes.  Though this project will only focus 
on nominal vermilion rockfish specimens collected through the 2019 survey 
field season, it may be advisable that tissue specimens collected aboard 
fishery-independent surveys as well as through fishery-dependent programs 
continue to be genotyped on an ongoing basis to support continued and timely 
monitoring of this economically and ecologically important species complex.


## Map
A map showing the scope of the two California `r spp` assessments and depicting a 
boundary 
at Point Conception (\PtC) that separates the two assessments is provided as Figure \@ref(fig:assess-area). The northern California
model is bounded by the California/Oregon border (\CAOR) and the southern California model is 
bounded by the U.S./ Mexico border at the south (Figure \@ref(fig:assess-area)). 
Cape Mendocino (\CapeM) is also noted as it is a management boundary for the 
Pacific Fishery Management Council (PFMC) "minor shelf rockfish" stock complex.


## Ecosystem Considerations

This stock assessment does not explicitly incorporate trophic interactions, 
habitat factors (other than as they inform relative abundance indices) or environmental 
factors into the assessment model, but a brief description of likely or potential 
ecosystem considerations are provided below. 

Vermilion/sunset rockfish are described as feeding on a wide range of both
pelagic and benthic prey items, including forage fish species such as anchovies 
and mesopelagic fishes, squid, krill and octopus, as well as sporadically abundant
pelagic organisms such as pyrosomes, salps and pelagic red crabs 
[@Phillips1964; @Love2002].  Interestingly, other rockfishes (either juvenile or 
adult stages) have not been 
documented as prey for vermilion, as they have been for other large *Sebastes* 
species such as cowcod, bocaccio, and yelloweye rockfish.  For the latter species, 
the idea of “cultivation effects,” in which adults crop down forage species that 
are potential competitors/predators of their own juveniles [@Walters2001], 
has been suggested by [@MacCall2002, @Baskett2006]. For example, Baskett et al. [-@Baskett2006] 
found that in such scenarios there could be alternative stable states in which 
either the overfished species or the smaller prey species could dominate.  While 
the sparse diet data for vermilion/sunset rockfish do not suggest such a process 
for this species complex, food habits data for vermilion/sunset are not robust, 
and the larger community processes on these rocky reef communities may also influence 
productivity and community composition regardless of the direct predation interactions. 
Pelagic and benthic juvenile vermilion and sunset rockfish are likely preyed upon by 
the same wide range of predators that prey on juveniles and adults of other rockfish 
species, including seabirds, piscivorous fishes, and marine mammals.  

As with most other rockfish and groundfish in the California Current, recruitment, 
or cohort (year-class) strength appears to be highly variable for the vermilion/sunset 
rockfish complex, with only a modest apparent relationship to estimated levels of spawning output.  
Oceanographic and ecosystem factors are widely recognized to be key drivers of
recruitment variability for most species of groundfish, as well as most elements
of California Current food webs.  Empirical estimates of recruitment from pelagic 
juvenile rockfish surveys have been used to inform incoming year class strength for 
some of these stocks, however vermilion and sunset rockfish are rarely encountered 
in these surveys.  Specifically, only 47 of nearly 300,000 total juvenile *Sebastes* 
encountered in juvenile surveys since 2001 were identified as vermilion or sunset 
rockfish [@Field2021].  Despite this, the results here suggest that at least a
reasonable fraction of recruitment variability for sunset and vermilion rockfish 
is shared with other rockfish and groundfish stocks throughout the California Current, 
many of which also had strong year classes in 1984, 1999 and 2015-2016.  Previous studies 
have demonstrated that large-scale oceanographic drivers, such as the relative transport 
of subarctic waters (typically indicated by relative sea level) tend to relate to a 
substantial fraction of overall groundfish recruitment trends and ecosystem 
productivity [@Stachura2014, @Schroeder2019].  Although it is feasible that 
ecosystem factors, the results of pre-recruit surveys for co-occurring species, 
or the results of other groundfish assessments might ultimately be used to 
forecast recruitment for more data-limited stocks such as vermilion/sunset,
as suggested by [@Thorson2014], such approaches would require more 
development and evaluation.  Consequently, environmental factors are not 
explicitly considered in this assessment.
