
## Data sources considered, but not used

`r Spp` are not well sampled by the following studies we considered as possible 
data sources.

*NWFSC Triennial Survey*

The \gls{s-tri} was first conducted by the \gls{afsc} in 1977, and the survey 
continued until 2004 [@Dark1994].
Its basic design was a series of equally-spaced east-to-west transects across 
the continential shelf from which searches for tows in a specific depth range were initiated.
The survey design changed slightly over time.
In general, all of the surveys were conducted in the mid summer through early fall.
The 1977 survey was conducted from early July through late September.
The surveys from 1980 through 1989 were conducted from mid-July to late September.
The 1992 survey was conducted from mid July through early October.
The 1995 survey was conducted from early June through late August.
The 1998 survey was conducted from early June through early August.
Finally, the 2001 and 2004 surveys were conducted from May to July.

Haul depths ranged from 91-457 m during the 1977 survey with no hauls shallower 
than 91 m.
Due to haul performance issues and truncated sampling with respect to depth, the 
data from 1977 were omitted from this analysis.
The surveys in 1980, 1983, and 1986 covered the US West Coast south to 
36.8\textdegree N latitude and a depth range of 55-366 m.
The surveys in 1989 and 1992 covered the same depth range but extended the 
southern range to 34.5\textdegree N (near Point Conception).
From 1995 through 2004, the surveys covered the depth range 55-500 m and 
surveyed south to 34.5\textdegree N.
In 2004, the final year of the \gls{s-tri} series, the \gls{nwfsc} \gls{fram} 
conducted the survey following similar protocols to earlier years.


*Alaska Fisheries Science Center Slope Survey* 

The \gls{s-aslope} operated during the months of October to November aboard the 
R/V _Miller Freeman_.
Partial survey coverage of the US West Coast occurred during the years 1988-1996 
and complete coverage (north of 34\textdegree 30\textquotesingle S) during the 
years 1997 and 1999-2001.
Typically, only these four years that are seen as complete surveys are included 
in assessments.


*Partnership for Interdisciplinary Studies of Coastal Oceans*

The Partnership for Interdisciplinary Studies of Coastal Oceans, 
[PISCO-UCSC](http://www.piscoweb.org/kelp-forest-study), conducts a number of surveys 
to monitor the kelp forests, one of which is a kelp forest fish survey. PISCO
has monitored fish population in the 0-20 m depth range as part of the 
Marine Life Protection Act (MLPA) since 1998.  Paired sites inside and outside MPAs 
are surveyed to monitor the long-term dynamics of the kelp forest ecosystem and provide 
insight into the effect of MPAs on kelp forest species. PISCO conducts the fish 
surveys from late July through September. At each site, benthic, midwater, and canopy 
scuba transects are conducted at 5, 10, 15, and 20 m depth.  All divers are trained 
in species identification.  Along each 30 m transect, divers enumerate all identifiable 
non-cryptic fish, and measure total length to the nearest centimeter.  PISCO surveys 
are conducted by the University of California Santa Cruz (UCSC) in central California and 
through the University of California Santa Barbara in southern California. 

*California Cooperative Oceanic Fisheries Investigations* 

The \Gls{calcofi} surveys began in 1951 and conducts quarterly cruises off southern & 
central California, collecting a suite of hydrographic and biological data on 
station and underway. Ichthyoplankon sampling with a paired bongo started in 1978. 
Data on larval abundance from the CalCOFI Ichthyoplankton survey have been used in 
stock assessments of several species, including bocaccio, cowcod and shortbelly 
rockfish.  Although the long-term dataset is limited to a small subset of species 
for which morphological identification of larvae has been possible, recent research 
has been successful at identifying a broader range of species based on genetic 
identification of larvae [@Thompson2016]. 
Vermilion rockfish cannot be identified morphologically in the ichthyoplankton 
samples. Of over 20,000 larvae identified in the 1998-2013 time period, only nine 
were vermilion rockfish, encountered in only about 1% of the hauls. Consequently, 
the data are insufficient at this time to use to inform relative abundance, although Thompson et al. 
[-@Thompson2017] do provide several relative abundance time series for other taxa, and 
future efforts may lead to better taxonomic resolution of historical or future collections.

*Rockfish Recruitment and Ecosystem Survey*

Since 1983, the SWFSC has conducted an annual midwater trawl survey for pelagic 
juvenile rockfish and other groundfish in the Central California region of the 
California Current ([-@Ralston2013] and references therein).  Due to concerns 
about mesoscale abundance patterns and a need for greater spatial representation 
in the data, including some apparent strong differences in spatial distribution 
patterns in the early 2000s [@Hastie2007; @Ralston2013], this survey was expanded 
to a broader spatial scale in the 2001-2004 period, and since 2004 most years have 
coastwide data from a combination of SWFSC, NWFSC and Cooperative Research surveys 
(see Field et al. [-@Field2021] for more complete details regarding coastwide 
pre-recruit data, and Sakmua et al. [-@Sakuma2016] and Friedman et al. [-@Friedman2018] 
for additional details and 
alternative applications of survey data). 

Vermilion frog..


*California Collaborative Research Project*

In 2017 the California Collaborative Research Project (CCFRP) expanded state-wide 
and samples four MPAs and associated references sites in southern California.  
Vermilion rockfish have been encountered at two of the MPAs (Carrington Point off 
Santa Rosa Island and South La Jolla) and observed in 27% of all drifts at these 
two locations. The STAT determined that the was too constrained spatially and 
temporally to be considered 
for an index of abundance. There are currently 262 lengths of vermilion available.
With additional years of data, this data set can be considered for inclusion in a 
future vermilion assessment.




*Southern California Bight Publicly Owned Treatment Works*

In the Southern California Bight, a number of monitoring programs exist to evaluate the potential consequences of effluent discharges from wastewater treatment facilities on the coastal marine environment.  As over 20 million people live within an hour’s drive of the ocean in this region, a major impact to this ecosystem includes a cumulative total of 1.5 billion liters of treated effluent each day to the ocean, originating from 17 major wastewater treatment plants [@Schiff2016].  Most of these publicly owned treatment works support monitoring programs to evaluate the impacts on water and sediment quality, and associated ecological communities.  For several, this includes bottom trawl surveys of coastal habitats, and data from the longest running trawl surveys, despite being limited spatially to waters closer to population centers, have previously been used in stock assessments of cowcod (*Sebastes levis*) and California scorpionfish (*Scorpaena guttata*)[@Dick2019; @Monk2017].  Cowcod were rarely encountered in these surveys, occurring in 139 of the 1896 trawls conducted by the most rigorous of the surveys, and the development of a relative abundance index required pooling data into five year “blocks” in order to provide plausible estimates of year effects.  The resulting index was not highly influential in the final assessment model [@Dick2019], and indeed the lumping of years was only acceptable in that model as recruitments were not estimated.  By contrast, California scorpionfish were frequently encountered in several of these surveys, with over 10,000 fish being observed (and measured) over the history of those surveys, and the resulting relative abundance index and length frequently data were very influential in the California scorpionfish assessment with respect to both trends and recruitment [@Monk2017].  As preliminary investigations suggested that vermilion rockfish are even more rare than cowcod in this survey, and because grouping years of data would be inappropriate where recruitments are being estimated, a more rigorous evaluation of these datasets was not developed for this assessment.  However, it could be feasible to consider such an evaluation in future stock assessments.

