# Assessment Model Diagnostics

## Sensitivity to Assumptions, Data, and Weighting

All sensitivities in this section use the **pre-STAR** base model.


To better understand how data from individual fishery sectors or scientific surveys affected assessment results, we excluded data sets from the likelihood, one fleet at a time (referred to here as a “drop-one” analysis). “Fleet” in this sense refers to either a fishing fleet or a survey “fleet.” To do this, we set “lambdas” (multipliers for each likelihood component) equal to zero. This is equivalent to removing the data from the model. When composition data were excluded, the selectivity parameters for that fleet were fixed at the base model estimates to standardize the size and age composition of harvested fish. When abundance indices were excluded, relevant catchability and ‘extraSE’ parameters associated with the index were not estimated. Composition data weights for the remaining fleets were kept consistent with the base model values. Results from all the ‘drop-one’ runs were compared to the base model using time series plots and tables containing likelihood components, parameter estimates and derived quantities.


Drop-one analysis of the northern California assessment revealed slightly larger variability in spawning output trends relative to the south, but all runs were still within the range of uncertainty estimated by the base model (Figure \@ref(fig:drop-spawnbio)). Removal of most fleets had little effect on terminal stock status, with best estimates in the vicinity of target biomass levels (Figure \@ref(fig:drop-bratio)). An exception was removal of the REC_PC fleet, which caused the best estimate of terminal depletion to drop just above the minimum stock size threshold. This suggests that the REC_PC data sets, together, favor a less-depleted stock relative to data from the other fleets. The strength of the 2016 year class is sensitive to the removal of fleet-specific data sets (Figure \@ref(fig:drop-recdev)). Removal of the REC_PR fleet produces the largest estimates of 2016 cohort size, and removal of the NWFSC_TWL fleet estimates a 2016 deviation that is less than half as large (but still positive). Uncertainty in the strength of this recent year class should be taken into consideration for short-term forecasts of stock abundance and yield. Changes in likelihoods, parameter estimates and derived quantities are recorded in Table \@ref(tab:drop-one). Comparison of likelihoods among drop-one scenarios should be treated with caution due to changes in the data sets that were fit in each model run.

### Sensitivity to Catch Uncertainty
To evaluate the influence of highly uncertain catch histories, the we both halved and doubled the  historical catches in the pre-STAR base model.  The historical catches tend to be far more uncertain than catches in the more recent and better documented era for rockfish (*Sebastes* spp.), as historically most rockfish were landed in mixed stock market categories.  However, relative to the somewhat elevated uncertainties described in the historical catch sensitivity analysis for southern California vermilion rockfish, there is less evidence for substantive bias in historical catches of vermilion rockfish north of Point Conception, where there is better evidence that vermilion rockfish made up a relatively modest fraction of the total catch. 

The halving and doubling of historical catches in the northern model did lead to substantial differences in estimates of stock status (Figures \@ref(fig:sens2-depl) and \@ref(fig:sens2-spr)). A doubling of historical catches restuled in a stock slightly above the MSST, and a substantially larger predicted biomass when historical catches were halved.  Equilibrium MSY estimates were also larger with greater historical catches (by approximately 32 tons) and reduced with lower historical catches.  The relative change in model fit, as reflected by the total negative log likelihood, was modest, with a slightly improved fit in the lower historical catch scenario, and a slightly poorer fit in the higher historical catch scenario. 



### Other Model Sensitivities
Results from the **pre-STAR** base model were compared to several alternative model specifications, as described below.

- Estimate the Beverton-Holt steepness parameter (*h*) rather than fixing it at the prior mean   (*h*=0.72); estimate uncertainty intervals for comparison to base
- Start recruitment deviations 5 years earlier than the base model configuration
- Start recruitment deviations 5 years later than the base model configuration
- Compare results based on the McAllister-Ianelli data weighting method (for composition data) to the Francis method used for the base model. 
- Mirror the recreational discard fleets’ selectivity curves to the corresponding retained fleets (PC or PR) rather than fitting to discard length comps as in the base model.



Trends in spawning output for the northern California assessment model were generally robust to this set of sensitivities (Figure \@ref(fig:sens1-spawnb)). Best estimates from all runs were within the estimated range of uncertainty for the base model. Steepness was estimated at a higher value than the prior mean (estimated at 0.94 vs. fixed at 0.72). Similarly, stock status did not vary greatly among this set of sensitivity runs, with only a minor increase in 2021 relative spawning output when using McAllister-Ianelli weights and a slight decrease when estimating steepness (Figure \@ref(fig:sens1-bratio)). The use of McAllister-Ianelli weights had the greatest impact on estimated recruitment deviations (Figure \@ref(fig:sens1-recdevs)). This weighting method significantly reduced the magnitude of the 2016 year class, and generally increased the variance of the estimated deviations. The McAllister-Ianelli method gives greater weight to the composition data for this model (Table \@ref(tab:data-weights)), and resulted in lower estimates of the male and female natural mortality rates (Table \@ref(tab:sens1)).

During the STAR panel review, the STAT presented results from several sensitivity runs that were completed after distribution of the draft assessment document. All runs were conducted with the pre-STAR base models. These included:  
- Fixing the natural mortality rate (M) to a value consistent with the observed maximum age when applying the Hamel prior (i.e., M = 5.4/80 = 0.07 $yr^{-1}$)  
- Assuming asymptotic (2-parameter) selectivity curves for all fleets, except for recreational discard and the NWFSC trawl survey)  
- Estimating domed (4-parameter) selectivity curves for all fleets, but allowing for asymptotic shapes when supported by the data.  
- Use of a 3-parameter, reparameterized Ricker stock-recruitment relationship instead of a standard, 2-parameter Beverton-Holt relationship.


The STAT compared several results from these runs to the pre-STAR base model, including time series of spawning output, relative spawning output, and recruitment deviations (Figures \@ref(fig:sens3a), \@ref(fig:sens3b), and \@ref(fig:sens3c)). Negative log likelihoods (total and by data type), parameter estimates, and derived quantities were also examined relative to the pre-STAR base (Table \@ref(tab:sens3)). Fixing $M$ at 0.07 degraded the overall fit to the data, increasing the likelihood by about 3 points. The model with forced asymptotic selectivity estimated a slightly higher natural mortality rates (female $M$ = 0.11, male $M$ = 0.10) and had a total negative likelihood that was over 30 points higher than the pre-STAR base model. Estimating 4 selectivity parameters per fleet (excluding the discard and NWFSC trawl survey) produced results similar to the pre-base model, with a slightly larger population scale. Parameters from a reparameterized Ricker stock-recruitment relationship were estimable (Table \@ref(tab:sens3)) with M fixed at base model values, but produced point results and a total likelihood that were generally consistent with the Beverton-Holt relationship assumed in the base model.


## Likelihood Profiles

Likelihood profiles were conducted for natural mortality ($M$), steepness ($h$) and the log of R0 (unfished recruitment) by fixing these parameters across a range of values and continuing to estimate the remaining parameters assuming the base model framework.  All models in this section use the **post-STAR** base models.

The profiles for natural mortality in the northern model (Figures \@ref(fig:m-profile), \@ref(fig:m-depl),  \@ref(fig:m-spawn), \@ref(fig:m-recruits), and \@ref(fig:m-recdevs)) suggest that this parameter is reasonably well informed between a range of approximately 0.07 and 0.11, a somewhat lower range of values than was estimated for the southern model. Interestingly, profiles for natural mortality in the north indicated that the length data were better fit by the model with a lower natural mortality rate, and the age data were better fit by a higher rate, a result that is in contrast to that observed in the southern model. Most of the indices were also better fit by a higher natural mortality rate, although the Deb Wilson-Vandenberg Index and the onboard observer index were better fit with lower natural mortality rates. As is typical, spawning output increased with decreasing natural mortality, such that the model estimate with $M$ = 0.05 was 1.5 times that of the model estimate when $M$ was assumed to be 0.12. Similarly, the model estimated depletion in 2020 was well above the target level, close to 70%, for the M=0.12 model, while the ending depletion was just barely over the minimum stock size threshold of 25% of the unfished level in the M=0.05 model (Figure \@ref(fig:m-depl)).  

A profile of steepness was conducted on values ranging from 0.30 to 0.90 in 0.10 increments.  The likelihood profiles (by component, and by component and fleet) are shown as  Figure \@ref(fig:h-profile), and the resulting model trajectories (spawning output, relative depletion, age-0 recruits, and recruitment deviations) are shown as Figures \@ref(fig:h-spawn), \@ref(fig:h-depl), \@ref(fig:h-recruits), and \@ref(fig:h-recdevs). The likelihood profiles show that the overall best fit to the data is associated with high steepness values, although the data were generally uninformative above steepness values of 0.5.  Overall the length data were not very informative, and there was some odd jumps in the likelihood in some fleets at very low (0.3) steepness values. Similarly the age data were only marginally informative, and suggested higher steepness values in general. Most of the indices also suggested higher steepness values, particularly the NWFSC hook and line survey index, although the Rec PC index had a significantly better fit at lower steepness values. Predictably, spawning output scaled down with higher steepness values and up with lower values, however the estimate of stock status in 2021 was actually more optimistic with lower steepness values and more pessimistic with higher steepness values.  The higher steepness runs were also more pessimistic with respect to historical (late 1980s through the early 2000s) stock status.       

A profile on the log of unfished recruitment was conducted on values ranging from 5.7 to 6.4 (the base model estimate was 6.07), and is shown as Figure \@ref(fig:r0-profile).  In general, age data was better fit by the model with higher values of R0, as was most of the survey data (as well as recruitment via likelihood penalties).  The DWV_onboard survey index and the Rec_PR were both somewhat better fit by the lower R0 values. All length data were either better fit to lower R0 values or were uninformative.  As with the southern model, spawning output is estimated to be greater with the higher R0 values, although the overall difference in scaling was minimal for early years.  Also consistent with the southern model result, the northern model result was more pessimistic with the lower R0 values, with the low R0 values being below the MSST and higher R0 values suggesting that relative spawning output is well above target levels (Figures \@ref(fig:r0-depl), \@ref(fig:r0-spawn), \@ref(fig:r0-recruits), and \@ref(fig:r0-recdevs)). As with the southern model, this is a result of corresponding model changes in the estimate of the natural mortality rate (which is estimated to be much lower in the low R0 model), such that the R0 profile is in many ways simply providing the same information as the profile on the natural mortality rate.  Additional profiles in which M is fixed may be helpful in evaluating model performance.

## Retrospective Analysis

All models in this section use the **post-STAR** base model.


A five year retrospective analysis was conducted on the northern base model by sequentially removing data, beginning with data from the year 2020.  Figures \@ref(fig:retro-spawnb), \@ref(fig:retro-bratio),  \@ref(fig:retro-recruits), and \@ref(fig:retro-recdevs) show the estimated spawning output, the estimated depletion, the recruitment deviation estimates and the estimated fit to the CCFRP index (which was the index most affected by the analysis).  The greatest impact of sequentially removing recent data was the declining estimate of the strength of the 2016 year class, a result similar to the southern model, as the length composition and index data that informed those year classes were removed.  There was also a slightly lesser reduction in the strength of the 2013 and 2014 year classes.  However, aside from a modest rescaling upwards of recruitment deviations, the spawning output and depletion estimates did not change by any significant measure, suggesting no concerning retrospective patterns (Table \@ref(tab:retro)).  Note that all composition data weights were held constant at the base model values during each run.





## Unresolved Problems and Major Uncertainties
This assessment treats populations north and south of Point Conception as separate, but there is likely larval or juvenile dispersal, and potentially some adult movement, among these areas.  Dispersal and movement rates are not well known.

The primary fishery-independent survey for West Coast groundfish, the NWFSC WCGBTS, does not sample rocky habitats where most vermilion rockfish are found, and thus does not provide a robust index of abundance.  An alternative survey, the CCFRP hook-and-line survey, provides a good signal for vermilion rockfish, including relative abundance and demographic structure inside and outside a number of MPAs. In addition to not including data from closed areas, many of the fishery-dependent indices are noisy, and some are not particularly well fit, such as the recreational PR dockside index.

Age data are limited and consequently growth and natural mortality estimates are uncertain.  There is an unusual pattern of tension among data sources inferred by the likelihood profiles, with age data suggesting a higher natural mortality rate and length data suggesting a lower *M*.  This is opposite the pattern seen in the southern assessment, and (very generally speaking) many other west coast groundfish assessments.

The model estimates a series of very low recruitment events throughout most of the 1970s, a period in which many other rockfish in this region experienced high levels of recruitment.  Recruitment patterns in more recent years generally follow those for other stocks.  It is possible that selectivity patterns changed, data are biased, model misspecification, or unknown ecosystem interactions could be responsible for this pattern.  
