\clearpage

# Acknowledgments (not required for draft assessments)
We gratefully acknowledge input and review from the STAR panel including John 
Budrick (STAR panel chair; California Department of Fish and Wildlife), 
Allan Hicks (International Pacific Halibut Commission),Matt Cieri (Center for 
Independent Experts), and Paul Medley (Center for Independent Experts). Thanks 
to the STAR panel advisors Gerry Richter (GAP) and Melissa Mandrup (GMT) for 
their expertise and additional guidance during the STAR panel. 
Thanks to the SWFSC ages and the NWSFC CAP lab for reading vermilion rockfish otoliths as well as all of the labs that participated in the vermilion otolith CARE exchange. We thank Melissa Head (Northwest Fisheries Science Center NMFS, NOAA), for producing analyses on maturity, Sabrina Beyer (UCSC) for providing data on fecundity and John Harms and John Wallace for providing insight into the NWFSC hook-and-line survey and interpretation of available genetics and ongoing research of the cryptic species pair. Additionally, we thank all of the CCFRP program partners for conducting and providing the available data.

