
<!--
moved to exec summary
{r, warning = FALSE, inclue = FALSE}
management <- readxl::read_xlsx("./tables/VRML_management_history.xlsx", sheet = "Management")  %>%
  mutate(across(c(2:13), ~ round(.,3)))
management$Area_landings = c("OFL", "ABC", "Total landings", 
                             "CA rec landings", "OR rec landings", 
                             "WA rec landings","Commercial landings", "Research",
                             "OFL", "ABC", "Total Landings", 
                             "CA rec landings", "Commercial landings", "Research")
colnames(management)[1] = ""



{r, management, results = 'asis'}
kableExtra::kbl(management, booktabs = TRUE, 
  caption = "Annual estimates of total mortality, overfishing limit (OFL), acceptable biological catch (ABC), annual catch limit (ACL) for vermilion. The ABC is equal to the ACL.  Data were obtained from the GEMM reports.",
escape = FALSE) %>%
kableExtra::pack_rows(group_label = paste0("North of 40",intToUtf8(176),"10\' N"), start_row = 1, end_row = 8) %>%
kableExtra::pack_rows(group_label = paste0("South of 40",intToUtf8(176),"10\' N"), start_row = 9, end_row = 14) %>%
  kable_styling(latex_options = "scale_down")


-->

```{r, warning = FALSE, inclue = FALSE}
timeseries <- read.csv("./tex_tables/TimeSeries.csv") %>%
  mutate_at(c(2:9), round,3)
```

```{r, results = 'asis'}
kableExtra::kbl(timeseries, booktabs = TRUE, longtable = TRUE,
                caption = "Time series of population estimates from the base model.",
                col.names = c("Year", "Total Biomass (mt)","Spawning Output","Total Biomass 4+ (mt)", "Fraction Unfished", "Age-0 Recruits", "Total Mortality (mt)","(1-SPR)/(1-SPR 50\\%)", "Exploitation Rate"),
                             label = "timeseries") %>%
  column_spec(1:9, width="1.5cm") %>%
  kableExtra::kable_styling(latex_options = "repeat_header", font_size = 8)


```


