\clearpage
# Figures

<!-- ====================================================================== --> 
<!-- ******************* Data Used in the Model *************************** --> 
<!-- ====================================================================== --> 


```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(base_loc, "plots", "data_plot2.png"), 
caption = "Summary of data sources used in the base model",
label = 'data-plot')
```	


<!-- ====================================================================== -->  
<!-- ****************** Catches Used in the Model ************************* --> 
<!-- ====================================================================== -->  

```{r, results = 'asis'}
add_figure(
filein = file.path(base_loc, "plots", "catch2 landings stacked.png"), 
caption = "Catches by fleet used in the base model",
label = 'catch')
```	

<!-- ======================================================================= -->
<!-- **********************  Length Samples ******************************** --> 
<!-- ======================================================================= -->


```{r, results = 'asis'}
#add in length comp plots with captions and labels
#fleets with length
#Fleet 7 rec_pc_discard doesn't have lengths in either model
fleets_w_lencomp <- c(1:6, 8:9, 11:max(model$nfleets))

for (i in fleets_w_lencomp) {
  add_figure(
    filein = dir(paste0(base_loc, "/plots"), 
                 pattern = paste0("comp_lendat_bubflt", i, "mkt0.*\\.png$"), full.names = TRUE),
    caption = paste0("Length composition data from the ", model$FleetNames_parsed[i]),
    label = paste0("len-data-", model$FleetNames_label[i])
  )

   add_figure(
    filein = dir(paste0(base_loc, "/plots"), 
                 pattern = paste0("comp_lendat_data_weighting_TA1.8_",
                                  model$FleetNames[i], ".png$"), full.names = TRUE),
    caption = paste0("Mean length for the ", 
                     model$FleetNames_parsed[i], " with 95 percent confidence intervals"),
    label = paste0('mean-com-len-data-', model$FleetNames_label[i])
  )

}
```
<!-- ======================================================================= -->
<!-- *************************     Biology     ***************************** --> 
<!-- ======================================================================= -->


```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(fig_loc, "oldfish.jpg"), 
caption = "Photograph of the *oldest* aged fish used in the assessment with annuli marked by B. Kamikawa (NWFSC).",
label = 'oldfish')
```

```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(fig_loc, "Reader 1 vs Reader 2.png"), 
caption = "Aging precision between initial and blind double reads for vermilion. 
Numbers in the bubbles are the sample sizes of otoliths cross-read.",
label = 'reader1reader2')
```	

```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(fig_loc, "True vs Reads (by reader).png"), 
caption = "True versus predicted age for two current age readers at the NWFSC 
from the ageing error software with unbiased reads for reader 1 and curvilinear 
bias for reader 1 and curvilinear standard deviation for both readers.",
label = 'truereads')
```	


<!-- ====================================================================== -->
<!-- *********************    Selectivity            ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(paste0(base_loc, "/plots"), "sel01_multiple_fleets_length1.png"), 
caption = "Selectivity at length by fleet",
label = 'selex')
```


<!-- ======================================================================= -->
<!-- ********************* Model Diagnostics ******************************* --> 
<!-- ======================================================================= -->


<!-- ======================================================================= -->
<!-- ********************** Fit to the Length Data ************************* --> 
<!-- ======================================================================= -->

```{r, results = 'asis'}
#add in length comp plots with captions and labels
#fleets with length
#Fleet 7 rec_pc_discard doesn't have lengths in either model
fleets_w_lencomp <- c(1:6, 8:9, 11:max(model$nfleets))

for (i in fleets_w_lencomp) {
  add_figure(
    filein = dir(paste0(base_loc, "/plots"), 
                 pattern = paste0("comp_lenfit_residsflt", i, "mkt0.*\\.png$"), full.names = TRUE),
    caption = paste0("Pearson residuals for the ", model$FleetNames_parsed[i], ". Closed 
                     bubbles are positive residuals (observed > expected) and open bubbles 
                     are negative residuals (observed < expected)"),
    label = paste0("len-pearson-", model$FleetNames_label[i])
  )

   add_figure(
    filein = dir(paste0(base_loc, "/plots"), 
                 pattern = paste0("comp_lenfit_data_weighting_TA1.8_",
                                  model$FleetNames[i], ".png$"), full.names = TRUE),
    caption = paste0("Mean lengths for the ", 
                     model$FleetNames_parsed[i], " with 95 percent confidence 
                     intervals based on current samples sizes"),
    label = paste0('mean-len-fit-', model$FleetNames_label[i])
  )

}
```


<!-- ======================================================================= -->
<!-- **************************** Time Series ****************************** --> 
<!-- ======================================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(base_loc, "plots", "ts7_Spawning_output_with_95_asymptotic_intervals_intervals.png"), 
caption = "Estimated time series of spawning output",
label = 'ssb')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(base_loc, "plots", "ts1_Total_biomass_(mt).png"), 
caption = "Estimated time series of total biomass",
label = 'tot-bio')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(base_loc, "plots", "ts9_Relative_spawning_output_intervals.png"), 
caption = "Estimated time series of relative spawning output",
label = 'depl')
```




<!-- ======================================================================= -->
<!-- ************************** Recruitment ******************************** --> 
<!-- ======================================================================= -->


```{r, results = 'asis'}
add_figure(
filein = file.path(base_loc, "plots", "ts11_Age-0_recruits_(1000s)_with_95_asymptotic_intervals.png"), 
caption = "Estimated time series of age-0 recruits (1000s)",
label = 'recruits')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(base_loc, "plots", "recdevs2_withbars.png"), 
caption = "Estimated time series of recruitment deviations",
label = 'rec-devs')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(base_loc, "plots", "SR_curve.png"), 
caption = "Stock-recruit curve. Point colors indicate year, with warmer colors indicating earlier years and cooler colors in showing later years",
label = 'bh-curve')
```

<!-- ======================================================================= -->
<!-- *********************** Reference Points ****************************** --> 
<!-- ======================================================================= -->


```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(base_loc, "plots", "SPR2_minusSPRseries.png"), 
caption = "Estimated 1 - relative spawning ratio (SPR) by year",
label = '1-spr')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(base_loc, "plots", "SPR4_phase.png"), 
caption = "Phase plot of the relative biomass (also referred to as fraction unfished) versus the SPR ratio where each point represents the biomass ratio at the start of the year and the relative fishing intensity in that same year. Lines through the final point show the 95 percent intervals based on the asymptotic uncertainty for each dimension. The shaded ellipse is a 95 percent region which accounts for the estimated correlations between the biomass ratio and SPR ratio",
label = 'phase')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(base_loc, "plots", "yield2_yield_curve_with_refpoints.png"), 
caption = "Equilibrium yield curve for the base case model. Values are based on the 2020
fishery selectivity and with steepness fixed at 0.72",
label = 'yield')
```



<!-- ======================================================================= -->
<!-- **************************   Sensitivity  ***************************** --> 
<!-- ======================================================================= -->





<!-- ======================================================================= -->
<!-- ************************** Likelihood Profile ************************* --> 
<!-- ======================================================================= -->






<!-- ======================================================================= -->
<!-- *******************     Retrospectives    ***************************** --> 
<!-- ======================================================================= -->







\newpage


