
\clearpage 

```{r, warning = FALSE, inclue = FALSE}
length.sample.size <- readxl::read_xlsx("./tables/sample sizes for vermilion composition data.xlsx", sheet = paste0(model.area, "_LEN")) %>%
  mutate(FLEET = paste0(FLEET,"(",FLEET_NO,")")) %>%
  dplyr::select(-FLEET_NO) %>%
  mutate(N_INIT_BASIS = gsub("\\_", " ",N_INIT_BASIS)) %>%
  mutate(N_INIT_BASIS = tolower(N_INIT_BASIS)) %>%
  mutate_at(vars(c(N_TRIPS, N_SAMPLES)), as.numeric) %>%
   mutate(N_TRIPS  = round(N_TRIPS, 2)) %>%
  select(-N_INIT_BASIS)
#  mutate(N_TRIPS  = if_else(grepl("fish/trip", N_INIT_BASIS), round(N_TRIPS,2), round(N_TRIPS,0)))



#sample size methods
inputN <- readxl::read_xlsx("./tables/sample sizes for vermilion composition data.xlsx", sheet = paste0(model.area, "_LEN")) %>%
  dplyr::select(YEAR, SOURCE, FLEET, FLEET_NO, N_INIT_BASIS) %>% 
  unique() %>%
  group_by(FLEET_NO, SOURCE, N_INIT_BASIS) %>%
    summarise(minYr = min(YEAR),
              maxYr = max(YEAR)) %>%
  mutate(yrs = paste0(minYr,"-",maxYr)) %>%
  dplyr::select(SOURCE, FLEET_NO, N_INIT_BASIS, yrs) %>%
  unique() %>%
  rename(`Initial Sample Size Basis` = N_INIT_BASIS)


age.sample.size <- readxl::read_xlsx("./tables/sample sizes for vermilion composition data.xlsx", sheet = paste0(model.area, "_AGE")) %>%
   mutate(FLEET = paste0(FLEET,"(",FLEET_NO,")")) %>%
   dplyr::select(-FLEET_NO)

```


```{r,length-sample-size, results = 'asis'}
kableExtra::kbl(length.sample.size, 
                longtable = TRUE, booktabs = TRUE, 
  caption = "Samples sizes of length composition data by year.",
  col.names = c("Source", "Year", "Fleet(#)", "Number fish", "Sample size", "Trips"),
 align = 'lllrrr', linesep = ""
) %>%
  column_spec(1, width = "2cm") %>%
  column_spec(2, width = "1cm") %>%
  column_spec(3, width = "4cm") %>%
  column_spec(4, width = "2cm") %>%
  column_spec(5, width = "3cm") %>%
  column_spec(6, width = "1cm") %>%
  kable_styling(latex_options = "repeat_header", font_size = 10)
```


```{r,length-inputN, results = 'asis'}
kableExtra::kbl(inputN, 
                booktabs = TRUE, 
  caption = "Basis for initial input samples sizes by fleet and years for the length composition data in the table above.", align = 'lllrrr',
linesep = ""
) %>%
  kable_styling(latex_options = "striped", font_size = 10)
```


\newpage

```{r, age-sample-size, results = 'asis'}
kableExtra::kbl(age.sample.size, linesep = "",
                longtable = TRUE, booktabs = TRUE, 
  caption = "Samples sizes of conditional age-at-length data by year.",
  col.names = c("Source", "Year", "Fleet(#)", "Number of fish")
) %>%
  column_spec(1, width = "3cm") %>%
  column_spec(2, width = "1cm") %>%
  column_spec(3, width = "4cm") %>%
  column_spec(4, width = "3cm") %>%
  kable_styling(latex_options = "repeat_header")#, full_width = FALSE)
```

