<!-- ======================================================================= -->
<!-- ****************************** Parameter ****************************** --> 
<!-- ======================================================================= -->



```{r, warning = FALSE, inclue = FALSE}
mod_params = model$parameters[-c(grep('Impl',model$parameters$Label),
							     grep('Fore',model$parameters$Label)),
                                (names(model$parameters) %in%
                                c("Num","Label","Value","Phase","Min",
                                  "Max","Status","Parm_StDev",
                                  "Pr_type","Prior","Pr_SD"))] 
mod_params[,'Value'] = round(as.numeric(mod_params[,'Value']),3)                                 
# Combine bounds into one column
mod_params$Min = paste('(', mod_params$Min, ', ', mod_params$Max, ')', sep='')
# Combine prior info to one column
mod_params$PR_type = ifelse(mod_params$Pr_type == 'No_prior' , 'None', paste(mod_params$Pr_type,' (', mod_params$Prior,  ', ', mod_params$Pr_SD, ')', sep = ''))
# Set long value to scientific notation
mod_params[mod_params$Label == "Wtlen_1_Fem",3] = format(mod_params[mod_params$Label == "Wtlen_1_Fem",3], scientific = TRUE)
mod_params[mod_params$Label == "Wtlen_1_Mal",3] = format(as.numeric(mod_params[mod_params$Label == "Wtlen_1_Mal",3]), scientific = TRUE)
mod_params[mod_params$Label == "Eggs_scalar_Fem",3] = format(as.numeric(mod_params[mod_params$Label == "Eggs_scalar_Fem",3]), scientific = TRUE)
mod_params[mod_params$Label == "L_at_Amax_Mal_GP_1",3] = round(as.numeric(mod_params[mod_params$Label == "L_at_Amax_Mal_GP_1",3]), 4)
mod_params[mod_params$Label == "VonBert_K_Mal_GP_1",3] = round(as.numeric(mod_params[mod_params$Label == "VonBert_K_Mal_GP_1",3]), 3)
mod_params[mod_params$Label == "CV_old_Mal_GP_1",3] = round(as.numeric(mod_params[mod_params$Label == "CV_old_Mal_GP_1",3]), 3)
# Remove the max, prior and prior sd columns
drops = c('Max', 'Prior', 'Pr_type', 'Pr_SD', 'Num')
mod_params = mod_params[, !(names(mod_params) %in% drops)]
rownames(mod_params) = c()
mod_params[,"Label"] = gsub("\\_", " ", mod_params[,"Label"])
mod_params[,"PR_type"] = gsub("\\_", " ", mod_params[,"PR_type"])
# Add column names
colnames(mod_params) = c('Parameter',
                         'Value',
                         'Phase',
                         'Bounds',
                         'Status',
                         'SD',
                         'Prior (Exp.Val, SD)')
```



```{r, paramstable, results = 'asis'}
kableExtra::kbl(mod_params, booktabs = T,
             caption = "List of parameters used in the base model, including estimated values and standard deviations (SD), bounds (minimum and maximum), estimation phase (negative values not estimated), status (indicates if parameters are near bounds), and prior type information (mean and SD).",
             align = 'l',
             longtable = TRUE)  %>%
  kable_styling(latex_options = c("repeat_header"), font_size = 8) %>%
  kableExtra::landscape()
```

<!-- ======================================================================= -->
<!-- ****************** Convergence Data Weighting ************************* --> 
<!-- ======================================================================= -->



```{r, warning = FALSE, inclue = FALSE}
dataweight.filein = list.files(path = table_loc, 
               #   pattern = glob2rx(print(paste0("drop1_table_",model.area, ".xlsx"))), 
                  pattern = glob2rx(paste0("Convergence_Francis_and_MI_",model.area, ".xlsx")), 
                  full.names = TRUE)
dataweight <- readxl::read_xlsx(dataweight.filein) %>%
  na_if(.,"NA") %>%
  mutate_at(vars(base), as.numeric) %>%
  mutate(across(where(is.numeric), round, 3)) 
```


```{r,data-weights, results = 'asis'}
kableExtra::kbl(dataweight, booktabs = TRUE, longtable = TRUE,
  caption = "Suggested data-weighting for length and age composition data using the McAllister-Ianelli and Francis approaches, after five tuning iterations to the pre-STAR base model.",
  linesep = "",
  col.names = c("Method","Data Type", "Fleet No.","Fleet Name", "Iteration 1", 
                "Iteration 2", "Iteration 3", "Iteration 4" , "Iteration 5",
                "Base Model") 
) %>%
 # column_spec(1, width = "2cm") %>%

  kable_styling(latex_options = c("repeat_header"), font_size = 8) %>%
  kableExtra::landscape()
```



```{r, warning = FALSE, inclue = FALSE}
timeseries <- read.csv(paste0(exec_tables_loc,"TimeSeries.csv")) %>%
  mutate_at(c(2:9), round,3)
```

```{r, results = 'asis'}
kableExtra::kbl(timeseries, booktabs = TRUE, longtable = TRUE, linesep = "",
                caption = "Time series of population estimates from the base model.", 
                align  = "c",
                escape = F,
                col.names = c("Year", "Total Biomass (mt)",
                              "Spawning Output ($10^6$ eggs)","Total Biomass 4+ (mt)", 
                              "Fraction Unfished", "Age-0 Recruits", 
                              "Total Mortality (mt)","$\\frac{1-SPR}{1-SPR_{50\\%}}$", 
                              "Exploitation Rate"),
                             label = "timeseries") %>%
  column_spec(1, width=".3in") %>%
  column_spec(2:6, width=".6in") %>%
  column_spec(7:9, width=".6in") %>%
  kableExtra::kable_styling(latex_options = "repeat_header", font_size = 8)


```


