<!-- ======================================================================= -->
<!-- **************************   Sensitivity  ***************************** --> 
<!-- ======================================================================= -->
\FloatBarrier
<!-- drop 1 -->

```{r, warning = FALSE, inclue = FALSE}
dropone.filein = list.files(path = table_loc, 
               #   pattern = glob2rx(print(paste0("drop1_table_",model.area, ".xlsx"))), 
                  pattern = glob2rx(paste0("drop1_table_",model.area, ".xlsx")), 
                  full.names = TRUE)
dropone <- readxl::read_xlsx(dropone.filein) %>%
  mutate(across(where(is.numeric), round, 3)) %>%
  filter(!grepl("Size", Label)) %>%
  setNames(gsub("_", " ", names(.))) %>%
  select(1:7)

dropone2 <- readxl::read_xlsx(dropone.filein) %>%
  mutate(across(where(is.numeric), round, 3)) %>%
  filter(!grepl("Size", Label)) %>%
  setNames(gsub("_", " ", names(.))) %>%
  select(c(1,8:ncol(.)))
```


```{r,drop-one, results = 'asis'}
kableExtra::kbl(dropone, booktabs = TRUE, 
  caption = "Likelihood components, parameter estimates and derived quantities from the leave one out analysis of the pre-STAR base model. Continued in the next table.",
  linesep = ""
) %>%
  add_header_above(c(" " = 2, "Fleet Removed" = 5)) %>%
 #  column_spec(1, width="1.4in") %>%
 #  column_spec(2:7, width=".5in") %>%
kableExtra::landscape()
```

```{r,drop-one2, results = 'asis'}
kableExtra::kbl(dropone2, booktabs = TRUE, 
  caption = "Likelihood components from the additional leave one out analysis of the pre-STAR base model. The column name is the fleet removed from the model.",
  linesep = ""
) %>%
#   column_spec(1, width="1.2in") %>%
#   column_spec(2:7, width=".6in") %>%

kableExtra::landscape()
```

<!-- ======================================================================= -->
<!-- ************************** Likelihood Profile ************************* --> 
<!-- ======================================================================= -->






<!-- ======================================================================= -->
<!-- *******************     Retrospectives    ***************************** --> 
<!-- ======================================================================= -->

```{r, warning = FALSE, inclue = FALSE}
retro.filein = list.files(path = table_loc, 
               #   pattern = glob2rx(print(paste0("drop1_table_",model.area, ".xlsx"))), 
                  pattern = glob2rx(paste0("retro_",model.area, ".xlsx")), 
                  full.names = TRUE)
retro <- readxl::read_xlsx(retro.filein) %>%
  mutate(across(where(is.numeric), round, 3)) %>%
  filter(!grepl("Size", Label))
```


```{r retro, results = 'asis'}
kableExtra::kbl(retro, booktabs = TRUE, 
  caption = "Likelihood components from the retrospective analysis removing one to five years of data of the pre-STAR base model.",
  linesep = ""
) %>%
kableExtra::landscape()
 # column_spec(1, width = "2cm") %>
 # kable_styling(latex_options = c("scale_down"), font_size = 10)
```


<!-- ======================================================================= -->
<!-- **************************   Sensitivity1  ***************************** --> 
<!-- ======================================================================= -->

```{r, warning = FALSE, inclue = FALSE}
sens1.filein = list.files(path = table_loc, 
               #   pattern = glob2rx(print(paste0("drop1_table_",model.area, ".xlsx"))), 
                  pattern = glob2rx(paste0("sensitivities_h_dev_MI_selex_",model.area, ".xlsx")), 
                  full.names = TRUE)
sens1 <- readxl::read_xlsx(sens1.filein) %>%
  mutate_at(vars(disc_selex), as.numeric) %>%
  mutate(across(where(is.numeric), round, 3)) %>%
  filter(!grepl("Size", Label))
```


```{r sens1, results = 'asis'}
kableExtra::kbl(sens1, booktabs = TRUE, 
  caption = "Likelihood components from additional sensitivity runs to estimating steepness, starting recruitment deviations in 1965 or 1975, McAllister-Ianelli data weighting and estimating discard selecitity for the pre-STAR base model.",
  linesep = ""
) %>%
 # column_spec(1, width = "2cm") %>%
  kable_styling(latex_options = c("scale_down")) #%>%
 # kableExtra::landscape()
```

<!-- ======================================================================= -->
<!-- **************************   Sensitivity3  ***************************** --> 
<!-- ======================================================================= -->

```{r, warning = FALSE, inclue = FALSE}
sens3.filein = list.files(path = table_loc, 
               #   pattern = glob2rx(print(paste0("drop1_table_",model.area, ".xlsx"))), 
                  pattern = glob2rx(paste0("sens3_",model.area, ".xlsx")), 
                  full.names = TRUE)
sens3 <- readxl::read_xlsx(sens3.filein) %>%
 # mutate_at(vars(disc_selex), as.numeric) %>%
  mutate(across(where(is.numeric), round, 3)) %>%
  filter(!grepl("Size", Label))
```


```{r sens3, results = 'asis'}
kableExtra::kbl(sens3, booktabs = TRUE, 
  caption = "Likelihood components from additional sensitivity runs conducted after the draft document was submitted, and before the STAR panel. Descriptions of each run are in the text and all models are sensitivities using the pre-STAR base model.",
  linesep = ""
) %>%
 # column_spec(1, width = "2cm") %>%
  kable_styling(latex_options = c("scale_down")) #%>%
 # kableExtra::landscape()
```



