
```{r, warning = FALSE, inclue = FALSE}
management <- readxl::read_xlsx("./tables/VRML_management_history.xlsx", sheet = "Management")  %>%
  mutate_at(2:12, funs(round(.,2)))
management$Area_landings = c("OFL", "ABC", "Total landings", 
                             "CA rec landings", "OR rec landings", 
                             "WA rec landings","Commercial landings", 
                             "OFL", "ABC", "Total Landings", 
                             "CA rec landings", "Commercial landings")
colnames(management)[1] = ""

```


```{r,management, results = 'asis'}
kableExtra::kbl(management, booktabs = TRUE, 
  caption = "Annual estimates of total mortality, overfishing limit (OFL), acceptable biological catch (ABC), annual catch limit (ACL) for vermilion. The ABC is equal to the ACL.  Data were obtained from the GEMM reports.",
  escape = FALSE) %>%
kableExtra::pack_rows("North of $\\CapeM$", start_row = 1, end_row = 7) %>%
kableExtra::pack_rows("South of $\\CapeM$", start_row = 8, end_row = 12) %>%
  kable_styling(latex_options = "scale_down")
```
