<!-- ====================================================================== --> 
<!-- ******************* Data Used in the Model *************************** --> 
<!-- ====================================================================== --> 

\FloatBarrier

```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(fig_loc, "assess_area.png"), 
caption = "Map of the assssment area with the 3 nm California state water boundary.  The northern California model includes areas from Point Conception to the California-Oregon border and the southern California assessment includes areas from Point Concpetion to the USA-Mexico border. The boundary at Cape Mendocino is a Pacific Fishery Management Council boundary for management of the stock complex, provided for reference",
label = 'assess-area')
```	

<!-- ====================================================================== -->  
<!-- ****************** Catches Used in the Model ************************* --> 
<!-- ====================================================================== -->  

```{r, results = 'asis'}
add_figure(
filein = file.path(base_loc_plots, "catch2 landings stacked.png"), 
caption = "Catch histories by fleet used in the base model 
              (Commercial hook-and-line =  COM_HKL,
                Commercial trawl = COM_TWL, Commercial net = COM_NET,
              Recreational party/charter retained = REC_PC, Recreational 
              private/rental retained = REC_PR, Recreational party/charter 
              dead discards = REC_PC_DIS, Recreational private/rental dead 
              discards = REC_PR_DIS)",
label = 'catch')
```



```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(base_loc_plots, "data_plot2.png"), 
caption = "Summary of data sources used in the base model. See the text for fleet descriptions",
label = 'data-plot')
```





```{r, results = 'asis'}
add_figure(
filein = file.path(fig_loc, "compare_pacfin_calcom.png"), 
caption = "Comparison of total California landings from CALCOM and PacFIN",
label = 'calcom-pacfin')
```

\FloatBarrier

