
<!-- ======================================================================= -->
<!-- *************************     Biology     ***************************** --> 
<!-- ======================================================================= -->


```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(fig_loc, "Reader 1 vs Reader 2.png"), 
caption = "Aging precision between initial and blind double reads for vermilion. 
Numbers in the bubbles are the sample sizes of otoliths cross-read",
label = 'reader1reader2')
```	


```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(fig_loc, "oldfish.jpg"), 
caption = "Photograph of the *oldest* aged fish used in the assessment with annuli marked by B. Kamikawa (NWFSC)",
label = 'oldfish')
```


```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(fig_loc, "True vs Reads (by reader).png"), 
caption = "True versus predicted age for two current age readers at the NWFSC 
from the ageing error software with unbiased reads for reader 1 and curvilinear 
bias for reader 1 and curvilinear standard deviation for both readers",
label = 'truereads')
```	



```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(base_loc,"plots", "numbers10_ageerror_matrix_1.png"),
caption = "Distribution of observed age at true age for ageing error type 1",
label = 'ageerror')
```




```{r, results = 'asis'}
sa4ss::add_figure(
  filein = file.path(fig_loc, "vermilion_functional_maturity.png"),
  caption = "Fitted logistic regression of estimated functional maturity as a function of fork length for vermilion rockfish",
  label = 'functional-maturity'
)
```


```{r, results = 'asis'}
sa4ss::add_figure(
  filein = file.path(base_loc,"plots", "bio6_maturity.png"),
  caption = "Maturity at length",
  label = 'maturity'
)
```






```{r, results = 'asis'}
sa4ss::add_figure(
  filein = file.path(fig_loc, "fitted_fec_len.png"),
  caption = "Fitted fecundity as a function of weight from samples of vermilion rockfish",
  label = 'fitted-fecundity'
)
```


```{r, results = 'asis'}
sa4ss::add_figure(
  filein = file.path(base_loc,"plots", "bio8_fecundity_wt.png"),
  caption = "Fecundity as a function of weight",
  label = 'fecundity'
)
```



```{r, results = 'asis'}
sa4ss::add_figure(
  filein = file.path(base_loc_plots, "bio11_spawningoutput_age.png"),
  caption = "Spawning output at age. This is the product of maturity and fecundity. When these processes are length-based they are converted into the age dimension using the matrix of length at age",
  label = 'spawnage'
)
```

\FloatBarrier

<!-- ======================================================================= -->
<!-- ***************************** Sex Ratios ****************************** --> 
<!-- ======================================================================= -->

```{r, results='asis'}
sex.ratio.filein = list.files(path = paste0(base_loc, "/plots"), 
                  pattern = glob2rx("^sexratio_len_flt*mkt0*.png$"), 
                  full.names = TRUE)
if(model.area =='SCA'){sex.ratio.order = c(3,2,1,4,5)}
if(model.area =='NCA'){sex.ratio.order = c(1:length(sex.ratio.filein))}
for (i in sex.ratio.order) {

   add_figure(
      filein = sex.ratio.filein[i],
      caption = paste0("Sex ratios for length comps, whole catch, ",
      fleet_info$FleetNames_parsed[fleet_info$fleet_ID==gsub(".*[flt]([^m]+)[m].*", "\\1", sex.ratio.filein[i])],". Observed sex ratios (points) with 75% intervals (vertical lines) calculated as a Jeffreys interval based on the adjusted input sample size. The model expectation is shown in the purple line"),
    label = paste0("sexratio-",  fleet_info$FleetNames_label[fleet_info$fleet_ID==gsub(".*[flt]([^m]+)[m].*", "\\1", sex.ratio.filein[i])], "-", i)
    #,
  #  width = 50,
  #  height = 50
  )
}
```

\FloatBarrier

<!--weight-length-->

```{r, results = 'asis'}
sa4ss::add_figure(
  filein = file.path(base_loc,"plots", "bio5_weightatsize.png"),
  caption = "Weight-length relationship",
  label = 'weightlength'
)
```

<!-- ======================================================================= -->
<!-- ************************    Growth   ********************************** --> 
<!-- ======================================================================= -->

```{r, results = 'asis'}
sa4ss::add_figure(
  filein = file.path(base_loc,"plots", "bio1_sizeatage.png"),
  caption = "Length at age in the beginning of the year (or season) in the ending year of the model. Shaded area indicates 95% distribution of length at age around estimated growth curve",
    label = 'fittedgrowth')
```


\FloatBarrier 
