
```{r, results = "asis"}
add_figure(
  filein = file.path(paste0(fig_loc,"/CV_of_Length_vs_Age.png")),
  caption = "Coefficient of variation of length at age for vermilion rockfish from the NWFSC hook-and-line survey",
  label = "cv-length-age"
)

```



<!-- ======================================================================= -->
<!-- ********************* Model Diagnostics ******************************* --> 
<!-- ======================================================================= -->

```{r, results = 'asis'}

if(model.area=='NCA'){
  add_figure(
    filein = file.path(paste0(fig_loc,"/jitter_preSTAR_base_NCA.png")),
    caption = "Results from 100 jittered runs of the pre-STAR base model.  Missing values indicate the run did not converge",
    label = "jitter"
  )
} else {
  add_figure(
    filein = file.path(paste0(fig_loc,"/jitter_preSTAR_base_SCA.png")),
    caption = "Results from 100 jittered runs of the pre-STAR base model",
    label = "jitter"
  )
}
```



<!-- ======================================================================= -->
<!-- ************************    Growth   ********************************** --> 
<!-- ======================================================================= -->



```{r, results = 'asis'}
sa4ss::add_figure(
  filein = file.path(base_loc,"plots", "bio1_sizeatage.png"),
  caption = "Length at age in the beginning of the year (or season) in the ending year of the model. Shaded area indicates 95% distribution of length at age around estimated growth curve",
    label = 'fittedgrowth')
```


<!-- ======================================================================= -->
<!-- ************************    Selectivity     *************************** --> 
<!-- ======================================================================= -->


\FloatBarrier 

```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(base_loc,"plots", "sel01_multiple_fleets_length1.png"), 
caption = "Selectivity at length by fleet",
label = 'selex-length-all')
```

\FloatBarrier 

```{r, results = 'asis'}
sa4ss::add_figure(
  filein = file.path(base_loc,"plots", "sel02_multiple_fleets_age1.png"),
  caption = "Selectivity at age derived from selectivity at length for multiple fleets",
  label = 'selex-age-all'
)
```

<!--time varying selectivity-->
```{r, results ='asis'}
plot_info = read.csv(file.path(base_loc,"plots", "plotinfotable_for_doc.csv"))
selex_time = plot_info %>%
  filter(grepl("sel03_len_timevary_surf", label)) %>%
  filter(grepl("sex1", label))
n_fleets_blocks = ifelse(model.area=="NCA",2,3)
filein = file.path(base_loc, "plots")
for (a in 1:n_fleets_blocks){
	cap = selex_time$caption[a]
	lab = selex_time$label[a]
	add_figure(filein = file.path(filein, selex_time$file[a]), 
			   caption = cap, 
			   label = lab)

}
```

\FloatBarrier 
<!--selectivity for fleets that are not mirrored-->

```{r, messages = FALSE, warnings = FALSE} 
#get the fleet info for fleets that have estimated selectivity
selex_params <- data.frame(model$parameters$Label[grep("DblN", model$parameters$Label)])
colnames(selex_params) = "A"
regexp <- "[[:digit:]]+"
selex_params <- selex_params %>%
   mutate(fleet_ID = stringr::str_extract(A,regexp)) %>%
 # mutate(fleet_ID = substr(A, nchar(A)-2+1, nchar(A)-1)) %>%
  dplyr::select(fleet_ID) %>%
  filter(fleet_ID>0) %>%
  unique
selex_fleets = left_join(selex_params, fleet_info)
selex_fleets$fleet_ID = as.numeric(selex_fleets$fleet_ID)
```


\FloatBarrier 

```{r, results='asis'}
j <- 1
for (i in selex_fleets$fleet_ID) {
    add_figure(
    filein = dir(paste0(base_loc, "/plots"), 
                 pattern = paste0("sel09_len_flt",i,"sex1.png$"), full.names = TRUE),
    caption = paste0("Female ending year selectivity for the ", selex_fleets$FleetNames_parsed[j]),
    label = paste0("endyr-selex-", selex_fleets$FleetNames_label[j])
#    ,
#    width = 50,
#    height = 50
  )
  j<- j + 1
}
```


\FloatBarrier 


