
<!-- ======================================================================= -->
<!-- ********************** Fit to the Length Data ************************* --> 
<!-- ======================================================================= -->

```{r, results = 'asis}
sa4ss::add_figure(
  filein = file.path(fig_loc, "comp_lenfit__aggregated_across_time.png"),
  caption = "Length comps, aggregated across time by fleet.
Labels 'retained' and 'discard' indicate discarded or retained sampled for each fleet. Panels without this designation represent the whole catch.",
  label = 'lenfits-all'
)
```



```{r, results = 'asis'}
#add in length comp plots with captions and labels
#fleets with length
#Fleet 7 rec_pc_discard doesn't have lengths in either model

for (i in unique(model$len_comp_fit_table$Fleet)) {
  add_figure(
    filein = dir(paste0(base_loc, "/plots"), pattern = paste0("comp_lenfit_residsflt", i, "mkt0.png$"), full.names = TRUE),
    caption = paste0("Pearson residuals for the ", model$FleetNames_parsed[i], ". Closed bubbles are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)"),
    label = paste0("len-pearson-", model$FleetNames_label[i]),
    width = 50,
    height = 50
  )

   add_figure(
    filein = dir(paste0(base_loc, "/plots"), 
                 pattern = paste0("comp_lenfit_data_weighting_TA1.8_",
                                  model$FleetNames[i], ".png$"), full.names = TRUE),
    caption = paste0("Mean length for REC_PR with 95% confidence intervals based on current samples sizes. Francis data weighting method TA1.8: thinner intervals (with capped ends) show result of further adjusting sample sizes based on suggested multiplier (with 95% interval) for length data from the ",model$FleetNames_parsed[i]),
    label = paste0('mean-len-fit-', model$FleetNames_label[i]),
    width = 50,
    height = 50
  )

}
```





<!-- ======================================================================= -->
<!-- ***************************** Sex Ratios ****************************** --> 
<!-- ======================================================================= -->

```{r, results='asis'}
plot_info = read.csv(file.path(mod_loc, "plots", "plotinfotable_for_doc.csv"))
len_fit = plot_info[which(plot_info$category == "CompDat"), ]
plot.vec = grep("comp_lendat_flt", len_fit$label)
filein = file.path(mod_loc, "plots")
for (a in plot.vec){
	cap = len_fit$caption[a]
	lab = len_fit$label[a]
	add_figure(filein = file.path(filein, len_fit$file[a]), 
			   caption = cap, 
			   label = lab)
}
```