<!-- ======================================================================= -->
<!-- *************************  Indices ************************************ --> 
<!-- ======================================================================= -->
```{r, results = 'asis'}
add_figure(
    filein = file.path(base_loc, "plots", "index9_standcpueall.png"),
    caption = "Standardized indices overlaid. Each index is rescaled to have mean observation = 1.0",
    label = 'cpueall',
    width = 50,
    height = 50)
```


```{r, results = 'asis'}
#add in length comp plots with captions and labels
#fleets with length

for (i in unique(model$cpue$Fleet_name)) {
  add_figure(
    filein = dir(paste0(base_loc, "/plots"), 
                 pattern = paste0("index5_logcpuefit_", i , "*\\.png$"), full.names = TRUE),
    caption = paste0("Fit to log index data on log scale for the ",fleet_info$FleetNames_parsed[fleet_info$FleetNames==i] ,". Lines indicate 95% uncertainty interval around index values based on the model assumption of lognormal error. Thicker lines (if present) indicate input uncertainty before addition of estimated additional uncertainty parameter"),
    label = paste0("log-cpue-", fleet_info$FleetNames_label[fleet_info$FleetNames==i]),
    width = 50,
    height = 50
  )

  add_figure(
    filein = dir(paste0(base_loc, "/plots"), 
                 pattern = paste0("index10_resids_SE_total_", i , "*\\.png$"), full.names = TRUE),
    caption = paste0("Residuals of fit to index for the ", i ,". Values are (log(Obs) - log(Exp))/SE where SE is the total standard error including any estimated additional uncertainty"),
    label = paste0("cpue-resid-", fleet_info$FleetNames_label[fleet_info$FleetNames==i]),
    width = 50,
    height = 50
  )
}
```





<!-- ======================================================================= -->
<!-- *************************  Age Comps ********************************** --> 
<!-- ======================================================================= -->





<!-- ======================================================================= -->
<!-- **********************  Age @ Length Comps **************************** --> 
<!-- ======================================================================= -->


```{r, results = 'asis'}
caal_fit <- plot_info %>%
  filter(category == "A@LComp") %>%
  filter(grepl("condAALfit", label))
filein = file.path(mod_loc, "plots")
for (a in 1:length(caal_fit)){
  
  cat("\\FloatBarrier")
	
  cap = caal_fit$caption[a]
	lab = caal_fit$label[a]
	
	add_figure(filein = file.path(filein, caal_fit$file[a]), 
			   caption = cap, 
			   label = lab)
}
```