<!-- ======================================================================= -->
<!-- **************************   Sensitivity  ***************************** --> 
<!-- ======================================================================= -->

<!-- drop 1-->

```{r, warning = FALSE, inclue = FALSE}
dropone.fig.filein = list.files(path = fig_loc,  
                  pattern = glob2rx(paste0("drop1_*",model.area, ".png")), 
                  full.names = TRUE)
```


```{r, results = 'asis'}
sa4ss::add_figure(
  filein = dropone.fig.filein[3] ,
  caption = "Change in the spawning output when a single fleet is removed from the model",
  label = 'drop-spawnbio'
)

sa4ss::add_figure(
  filein = dropone.fig.filein[1] ,
  caption = "Change in the fraction of unfished biomass when a single fleet is removed from the model",
  label = 'drop-bratio'
)

sa4ss::add_figure(
  filein = dropone.fig.filein[2] ,
  caption = "Change in the recruitment deviations when a single fleet is removed from the model",
  label = 'drop-recdev'
)
```


<!--john catch sens-->


```{r, warning = FALSE, inclue = FALSE}
sens2.fig.filein = list.files(path = fig_loc,  
                  pattern = glob2rx(paste0("sens2*",model.area, ".png")), 
                  full.names = TRUE)
```


```{r, results = 'asis'}
sa4ss::add_figure(
  filein = sens2.fig.filein[1] ,
  caption = "Change in depletion when historical catches are modified",
  label = 'sens2-depl'
)

sa4ss::add_figure(
  filein = sens2.fig.filein[2] ,
  caption = "Change in the relative SPR when historical catches are modified",
  label = 'sens2-spr'
)
```

<!-- ======================================================================= -->
<!-- ************************** Likelihood Profile ************************* --> 
<!-- ======================================================================= -->


```{r, warning = FALSE, inclue = FALSE}
h.fig.filein = list.files(path = fig_loc,  
                  pattern = glob2rx(paste0("^h_*",model.area,".png")),
                  full.names = TRUE)

M.fig.filein = list.files(path = fig_loc,  
                  pattern = glob2rx(paste0("^M*",model.area,".png")),
                  full.names = TRUE)

R0.fig.filein = list.files(path = fig_loc,  
                  pattern = glob2rx(paste0("^R0*",model.area,".png")),
                  full.names = TRUE)

```

<!----nat M--->

```{r, results = 'asis'}
sa4ss::add_figure(
  filein = M.fig.filein[2] ,
  caption =  "Likelihood profile across natural mortality values for each data type",
  label = 'm-profile'
)

sa4ss::add_figure(
  filein = M.fig.filein[1] ,
  caption =  "Trajectories of depletion across values of female natural mortality",
  label = 'm-depl'
)

sa4ss::add_figure(
  filein = M.fig.filein[3] ,
  caption =  "Trajectories of spawning output across values of female natural mortality",
  label = 'm-spawn'
)
```

<!--steepness-->

```{r, results = 'asis'}
sa4ss::add_figure(
  filein = h.fig.filein[2] ,
  caption =  "Likelihood profile across steepness values for each data type",
  label = 'h-profile'
)

sa4ss::add_figure(
  filein = h.fig.filein[1] ,
  caption =  "Trajectories of depletion across values of steepness",
  label = 'h-depl'
)

sa4ss::add_figure(
  filein = h.fig.filein[3] ,
  caption =  "Trajectories of spawning output across values of steepness",
  label = 'h-spawn'
)
```


```{r, results = 'asis'}
sa4ss::add_figure(
  filein = R0.fig.filein[2] ,
  caption =  "Likelihood profile across R0 values for each data type",
  label = 'r0-profile'
)

sa4ss::add_figure(
  filein = R0.fig.filein[1] ,
  caption =  "Trajectories of depletion across values of R0",
  label = 'r0-depl'
)

sa4ss::add_figure(
  filein = R0.fig.filein[3] ,
  caption =  "Trajectories of spawning output across values of R0",
  label = 'r0-spawn'
)
```





<!-- ======================================================================= -->
<!-- *******************     Retrospectives    ***************************** --> 
<!-- ======================================================================= -->
```{r, include = FALSE, warning = FALSE}
retro.fig.filein = list.files(path = fig_loc,  
                  pattern = glob2rx(paste0("retro_*",model.area, ".png")), 
                  full.names = TRUE)

```


```{r, results = 'asis'}
sa4ss::add_figure(
  filein = retro.fig.filein[1] ,
  caption = "Change in the spawning output when the most recent 5 years of data area removed sequentially",
  label = 'retro-spawnb'
)


sa4ss::add_figure(
  filein = retro.fig.filein[3] ,
  caption =  "Change in the fraction of unfished biomass when the most recent 5 years of data area removed sequentially",
  label = 'retro-bratio'
)

sa4ss::add_figure(
  filein = retro.fig.filein[2] ,
  caption = "Change in the recruitment deviations when the most recent 5 years of data area removed sequentially",
  label = 'retro-recdev'
)
```



<!-- ======================================================================= -->
<!-- *******************     Other sensitivities**************************** --> 
<!-- ======================================================================= -->

```{r,include = FALSE, warning = FALSE}
sens1.fig.filein = list.files(path = fig_loc,  
                  pattern = glob2rx(paste0("sens01*",model.area, ".png")), 
                  full.names = TRUE)
```


```{r, results = 'asis'}
sa4ss::add_figure(
  filein = sens1.fig.filein[3] ,
  caption = "Change in the trajectory of spawning output to a series of model sensitivity runs",
  label = 'sens1-spawnb'
)


sa4ss::add_figure(
  filein = sens1.fig.filein[1] ,
  caption =  "Change in the fraction of unfished biomass to a series of model sensitivity runs",
  label = 'sens1-bratio'
)

sa4ss::add_figure(
  filein = sens1.fig.filein[2] ,
  caption = "Change in the recruitment deviations to a series of model sensitivity runs",
  label = 'sens1-recdev'
)
```
<!-- ======================================================================= -->
<!-- *******************    Other sensitivities 3**************************** --> 
<!-- ======================================================================= -->

```{r,include = FALSE, warning = FALSE}
sens1.fig.filein = list.files(path = fig_loc,  
                  pattern = glob2rx(paste0("sens3*",model.area, ".png")), 
                  full.names = TRUE)
```


```{r, results = 'asis'}
sa4ss::add_figure(
  filein = sens3.fig.filein[1] ,
  caption = "Change in the trajectory of spawning output to a series of model sensitivity runs",
  label = 'sens3a'
)


sa4ss::add_figure(
  filein = sens3.fig.filein[2] ,
  caption =  "Change in the fraction of unfished biomass to a series of model sensitivity runs",
  label = 'sens3b'
)

sa4ss::add_figure(
  filein = sens3.fig.filein[3] ,
  caption = "Change in the recruitment deviations to a series of model sensitivity runs",
  label = 'sens3c'
)
```