---
geometry: margin=1in
month: "`r format(Sys.Date(), '%B')`"
year: "`r format(Sys.Date(), '%Y')`"
params:
    model: 2
preamble: |
output:
  sa4ss::techreport_pdf:
    default
  bookdown::pdf_document2:
    keep_tex: true
    keep_md: true
lang: en
papersize: a4
---



<!--chapter:end:00a.Rmd-->




<!--chapter:end:00authorsnorth.Rmd-->




<!--chapter:end:00authorssouth.Rmd-->

---
bibliography:
  - sa4ss.bib
---

<!--chapter:end:00bibliography.Rmd-->

---
title: The status of Vermilion Rockfish (_Sebastes miniatus_) and Sunset Rockfish (_Sebastes crocotulus_) in U.S. waters off the coast of California north of Pt. Conception in 2021
---

<!--chapter:end:00titlenorth.Rmd-->

---
title: The status of Vermilion Rockfish (_Sebastes miniatus_) and Sunset Rockfish (_Sebastes crocotulus_) in U.S. waters off the coast of California south of Pt. Conception in 2021
---

<!--chapter:end:00titlesouth.Rmd-->

\pagebreak
\pagenumbering{roman}
\setcounter{page}{1}

\renewcommand{\thetable}{\roman{table}}
\renewcommand{\thefigure}{\roman{figure}}


\setlength\parskip{0.5em plus 0.1em minus 0.2em}

<!--chapter:end:01a.Rmd-->


# Executive Summary{-}

Placeholder


## Stock{-}
## Landings{-}
## Data and Assessment{-}
## Stock Biomass{-}
## Recruitment{-}
## Exploitation Status{-}
## Reference Points{-}
## Management Performance{-}
## Unresolved Problems and Major Uncertainties{-}
## Decision Table{-}
## Research and Data Needs{-}

<!--chapter:end:01executive.Rmd-->

\pagebreak
\setlength{\parskip}{5mm plus1mm minus1mm}
\pagenumbering{arabic}
\setcounter{page}{1}
\renewcommand{\thefigure}{\arabic{figure}}
\renewcommand{\thetable}{\arabic{table}}
\setcounter{table}{0}
\setcounter{figure}{0}

<!--chapter:end:10a.Rmd-->


# Introduction

Placeholder


## Basic Information
## Early Life History

<!--chapter:end:11a-introduction-bio.Rmd-->

## Historical and Current Fishery Information
Replace text.

## Summary of Management History and Performance
Replace text.



##Management Performance

## Foreign Fisheries
Replace text.



<!--chapter:end:11b-introduction-fishery.Rmd-->

# Data
A description of each data source is provided below (Figure).

<!--chapter:end:20-data.Rmd-->

## Fishery-Dependent Data

###Commercial Landings and Discards

*Commercial Landings Prior to 1916*

For landings estimates prior to 1916, we based our reconstruction on the total rockfish catches reported in a summary of early California fisheries landings by Sette and Fielder [-@Sette1928] for the years 1888, 1892, 1895, 1899, 1904, 1908 and 1915.  No rockfish were reported for 1888, thus we assumed no catches for that year and interpolated the catches between 0 and the 1892 catches (total of 834 tons) reported.  Similarly, catches between the reported years were interpolated assuming a straight linear trend between the years reported.  We used a ratio-estimator derived from the catch reconstruction fraction of vermillion rockfish in total rockfish landings for the 1916 to 1919 period (the ratio for a comparable five year period was nearly identical).  We apportioned the catches north and south of Point Conception based on ratio estimators that used the same assumptions used to apportion catches in the reconstruction time period (1916-1968).  The catch reconstruction estimates indicated that vermillion made up slightly under 1% of the total rockfish catches during the early (1916-1919) time period, although the estimates indicate a slightly larger fraction (1.5%) of total catches south of Conception relative to the fraction of total catches to the north (0.9%).  However, it is likely that the reconstruction is overestimating the fraction of smaller and/or more deeply distributed species relative to larger, shallower species as the reconstruction is based on the species composition data collected from market category samples in the late 1970s and early 1980s.  The fishery has been shown to have progressed over time from a shallower, more nearshore distribution of effort to one in which deeper and more offshore waters were targeted [@Miller2014].  The notion that vermillion catches may have been greater is also consistent with the recognition by Roedel [-@Roedel1948] that during the 1930s and 1940s vermillion were “One of the more important commercial species, it is one of three leading species in Southern California." However, by the time of that report, vermillion represented 5 to 8% of the southern California catch (based on Ralston et al. [-@Ralston2010]), much more than at the beginning of the time series.  Future efforts to improve historical catch reconstructions by accounting for the shift in effort over time to deeper waters should continue to be flagged as a research need. 


<!--chapter:end:21b-fishery-commercial.Rmd-->

## Fishery-Dependent Data

<!--chapter:end:21c-fishery-recreational.Rmd-->

## Fishery-Independent Data

<!--chapter:end:21d-survey-mrfss.Rmd-->

## Fishery-Independent Data

<!--chapter:end:21e-survey-crfs.Rmd-->

## Fishery-Dependent Data

<!--chapter:end:21f-.Rmd-->

### \acrlong{s-wcgbt}

The \Gls{s-wcgbt} is based on a random-grid design;
covering the coastal waters from a depth of 55-1,280 m [@bradburn_2003_2011].
This design generally uses four industry-chartered vessels per year assigned to a roughly equal number of randomly selected grid cells and divided into two 'passes' of the coast.
Two vessels fish from north to south during each pass between late May to early October.
This design therefore incorporates both vessel-to-vessel differences in catchability,
as well as variance associated with selecting a relatively small number (approximately 700) of possible cells from a very large set of possible cells spread from the Mexican to the Canadian borders.

<!--chapter:end:21f-survey-wcgbts.Rmd-->

### \acrlong{s-tri}

The \gls{s-tri} was first conducted by the \gls{afsc} in 1977, and the survey continued until 2004 [@weinberg_2001_2002].
Its basic design was a series of equally-spaced east-to-west transects across the continential shelf from which searches for tows in a specific depth range were initiated.
The survey design changed slightly over time.
In general, all of the surveys were conducted in the mid summer through early fall.
The 1977 survey was conducted from early July through late September.
The surveys from 1980 through 1989 were conducted from mid-July to late September.
The 1992 survey was conducted from mid July through early October.
The 1995 survey was conducted from early June through late August.
The 1998 survey was conducted from early June through early August.
Finally, the 2001 and 2004 surveys were conducted from May to July.

Haul depths ranged from 91-457 m during the 1977 survey with no hauls shallower than 91 m.
Due to haul performance issues and truncated sampling with respect to depth, the data from 1977 were omitted from this analysis.
The surveys in 1980, 1983, and 1986 covered the US West Coast south to 36.8\textdegree N latitude and a depth range of 55-366 m.
The surveys in 1989 and 1992 covered the same depth range but extended the southern range to 34.5\textdegree N (near Point Conception).
From 1995 through 2004, the surveys covered the depth range 55-500 m and surveyed south to 34.5\textdegree N.
In 2004, the final year of the \gls{s-tri} series, the \gls{nwfsc} \gls{fram} conducted the survey following similar protocols to earlier years.

<!--chapter:end:21g-survey-nwfschl.RMd-->

### \acrlong{s-ccfrp}

Since 2007, the \Gls{s-ccfrp} has monitored several areas in California to evaluate the performance of \Gls{mpa}s
and understand nearshore fish populations
[@Wendt2009; @Starr2015].
In 2017, the survey expanded beyond the four \Gls{mpa}s in central California
(A&ntilde;o Nuevo, Point Lobos, Point Buchon, and Piedras Blancas)
to include the entire California coast.
Fish are collected by volunteer anglers aboard \Gls{cpfv}s guided by one of the following academic institutions based on proximity to fishing location:
Humboldt State University;
Bodega Marine Laboratories;
Moss Landing Marine Laboratories;
Cal Poly San Luis Obispo;
University of California, Santa Barbara; and
Scripps Institution of Oceanography.

Surveys consist of fishing with hook-and-line gear for 30-45 minutes within randomly chosen 500 by 500 m grid cells within and outside \Gls{mpa}s.
Prior to 2017, all fish were measured for length and release or descended to depth;
since then, some were sampled for otoliths and fin clips.


<!--chapter:end:21h-survey-ccfrp.Rmd-->

### \acrlong{s-aslope}

The \gls{s-aslope} operated during the months of October to November aboard the R/V _Miller Freeman_.
Partial survey coverage of the US west coast occurred during the years 1988-1996 and complete coverage (north of 34\textdegree 30\textquotesingle S) during the years 1997 and 1999-2001.
Typically, only these four years that are seen as complete surveys are included in assessments.

<!--chapter:end:21s-aslope.Rmd-->

## Biological Data


### Length and Age Compositions

Differences in length compositions and length-at-age were explored 
north and south of Pt. Conception prior to any modelling. There are 
currently no available data to separate sunset and vermilion rockfishes.


Length compositions were provided from the following sources:

*North of Pt. Conception*

\begin{itemize}[noitemsep,nolistsep,topsep=0pt]
  \item Commercial sources
    \begin{itemize}[noitemsep,nolistsep]
      \item CALCOM (1978-2020)   
     \end{itemize}  
  \item Recreational sources    
    \begin{itemize}[noitemsep,nolistsep]
       \item Miller and Gotshall dockside survey (1959-1960)
       \item CPFV samples from Commercial port samplers (1978-1979)
       \item Deb Wilson-Vandenberg's onboard observer survey (1988-1998)
       \item MRFSS dockside survey (1980-2003)     
       \item CRFS onboard and dockside survey (2004-2019)
     \end{itemize}
    \item Fishery-independent surveys
      \begin{itemize}[noitemsep,nolistsep]
        \item CCFRP hook-and-line survey (2007-2018) 
        \item West Coast Groundfish Bottown Trawl Survey  (2003-2019) 
   \end{itemize}
\end{itemize}


*South of Pt. Conception*

\begin{itemize}[noitemsep,nolistsep,topsep=0pt]
  \item Commercial sources
    \begin{itemize}[noitemsep,nolistsep]
      \item CALCOM (1978-2020)   
    \end{itemize}
  \item Recreational sources     
    \begin{itemize}[noitemsep,nolistsep]
      \item Ally et al. onboard observer survey (1986-1989)
      \item Collins and Crooke onboard observer survey (1975-1978)  
      \item MRFSS dockside survey (1980-2003)     
      \item CRFS onboard and dockside survey (2004-2018)
    \end{itemize}
  \item Fishery-independent surveys
     \begin{itemize}[noitemsep,nolistsep]
        \item NWFSC Hook-and-Line Survey (2004-2019) 
        \item West Coast Groundfish Bottown Trawl Survey (2003-2019) 
   \end{itemize}
\end{itemize}




The length composition of all fisheries aggregated across time by fleet is in Figure
\ref{fig:comp_lendat_aggregated_across_time} and Table \ref{tab:length_samples_survey}. 
Descriptions and details of the length composition data are in the above section 
for each fleet or survey.

### Age Structures


**External Fits to Growth**


Fits to the von Bertalanffy growth curve [@vonB1938], 
$L_i = L_{\infty}e^{(-k[t-t_0])}$, where $L_i$ is the length (cm) at age $i$, $t$ is age in 
years, $k$ is rate of increase in growth, $t_0$ is the intercept, and $L_{\infty}$ 
is the asymptotic length, were explore by species and sex. 



### Ageing Precision and Bias

Uncertainty in ageing error was estimated using a collection of 357 `r spp` 
otoliths with two age reads between the NWFSC (reader 1, B. Kamikawa) and the 
SWFSC (reader 2, D. Watters) (Figure \@ref(fig:fig-reader1reader2)).
Age-composition data used in the model were from a number of sources described 
above. The same readers aged otoliths for both `r spp` stock assessmetnt models. 
Age reader 1 read all of the otoliths for the southern model and both readers read 
otoliths for the northern California model. In addition to the otoliths from these 
two regions, the same two readers aged fish for a Committee of Age Reading Experts 
(CARE)exchange among four ageing labs, initiated by the SWFSC.

Ageing error was estimated using publicly available software [@Thorson2012].
The software setting for bias was set to unbiased for reader 1 who was more 
experienced. The $\Delta AIC$ among the top three models was less than two. The 
best fitting model selected curvilinear bias for reader 1 and curvilinear standard 
deviation for both readers.  
An analysis of ageing error removing one fish aged at 88 by reader 1 and 78 by reader 2 
selected the the model with reader 2 as unbiased and curvilinear standard deviation 
(Figure \@ref(fig:fit-oldfish)). The reading of the oldest aged fish falls within the 95\% confidence 
internal using this model (Figure \@ref(fig:fig-truereads)).  
The latter model was selected for use in the assessment. 
 

The resulting estimate indicated a standard deviation in age readings 
increasing from 0.001 years at age 0 to a standard deviation of 2.37 years at age 70, 
the first year of the plus group in the assessment model.



### Maturation and Fecundity



### Natural Mortality

Natural mortality was not directly measured, so life-history based empirical relationships were used. The Natural Mortality Tool (NMT; https://github.com/shcaba/Natural-Mortality-Tool), a Shiny-based graphical user interface allowing for the application of a variety of natural mortality estimators based on measures such as longevity, size, age and growth, and maturity, was used to obtain estimates of natural mortality. The NMT currently provides 19 options, including the Hamel [-@Hamel2015] method, which is a corrected form of the Then et al. [-@Then2018] functional regression model and is a commomly applied method for west coast groundfish. The NMT also allows for the construction of a natural mortality prior weighted across methods by the user. 




### Sex Ratio

No information on the sex ratio at birth was available so it was assumed to be 50:50. 


### Length-Weight Relationship

The length(cm)-weight(kg) relationship for `r spp` was estimated outside the 
model using California biological data available from fishery-independent 
data sources. The estimated length-weight relationship for female fish was $W$=`r format(model$MGparmAdj$Wtlen_1_Fem[1], scientific = TRUE)`$L$^`r round(model$MGparmAdj$Wtlen_2_Fem[1],2)`^ and males at $W$=`r format(model$MGparmAdj$Wtlen_1_Mal[1], scientific = TRUE)`$L$^`r round(model$MGparmAdj$Wtlen_2_Mal[1], 2)`^ (Figure xx).



### Steepness

The Thorson-Dorn rockfish prior (developed for use West Coast rockfish assessments) conducted by James Thorson (personal communication, NWFSC, NOAA) and reviewed and endorsed by the Scientific and Statistical Committee (SSC) in 2017, has been a primary source of information on steepness for rockfishes. This approach, however, was subsequently rejected for future analysis in 2019 when the new meta-analysis resulted in a mean value of approximately 0.95. In the absence of a new method for generating a prior for steepness the default approach reverts to the previously endorsed method, the 2017 prior for steepness ($h$; beta distribution with $\mu$=`r round(model$parameters[model$parameters$Label == "SR_BH_steep","Value"],2)` and $\sigma$=0.15) is retained.  

<!--chapter:end:22biology.Rmd-->

## Environmental and Ecosystem Data

<!--chapter:end:23enviro.Rmd-->





<!--chapter:end:30model-platform.Rmd-->





<!--chapter:end:30model-previous-assess.Rmd-->





<!--chapter:end:30model-priors.Rmd-->

# Assessment Model








<!--chapter:end:30model.Rmd-->

## Summary of Previous Assessments and Reviews


### History of Modeling Approaches (not required for an update assessment)


### Most Recent STAR Panel and SSC Recommendations (not required for an update assessment)


### Response to Groundfish Subcommittee Requests (not required in draft)

<!--chapter:end:31summary.Rmd-->

## Model Structure and Assumptions


### Model Changes from the Last Assessment (not required for an update assessment)


### Modeling Platform and Structure
General model specifications (e.g., executable version, model structure, definition of fleets and areas)


### Model Parameters
Describe estimated vs. fixed parameters, priors

### Key Assumptions and Structural Choices

<!--chapter:end:32structure.Rmd-->



## Base Model Results
### Parameter Estimates
### Growth (Length-at-Age)
### Fits to the Data
### Population Trajectory
### Reference Points

<!--chapter:end:33results.Rmd-->

## Model Diagnostics
Describe all diagnostics

### Convergence

### Sensitivity Analyses

### Retrospective Analysis

### Likelihood Profiles

### Unresolved Problems and Major Uncertainties

<!--chapter:end:34diagnostics.Rmd-->

# Management 

## Reference Points

## Unresolved Problems and Major Uncertainties

## Harvest Projections and Decision Tables

## Evaluation of Scientific Uncertainty

## Research and Data Needs

<!--chapter:end:40management.Rmd-->

# Acknowledgments
Here are all the mad props!

<!--chapter:end:41acknowledgments.Rmd-->

\clearpage
# Tables


<!--chapter:end:52tables.Rmd-->


# Figures

Placeholder



<!--chapter:end:53figures.Rmd-->





#Deb Wilson-Vandenberg Index of Abundance

```{r, child = "indices/vermilion_DebWV_onboard_writeup_NCA.md"}
```


<!--chapter:end:60indicesappendices.Rmd-->


# Executive Summary{-}

Placeholder


## Stock{-}
## Landings{-}
## Data and Assessment{-}
## Stock Biomass{-}
## Recruitment{-}
## Exploitation Status{-}
## Reference Points{-}
## Management Performance{-}
## Unresolved Problems and Major Uncertainties{-}
## Decision Table{-}
## Research and Data Needs{-}
## Basic Information
## Early Life History
## Historical and Current Fishery Information
## Summary of Management History and Performance
## Foreign Fisheries
## Biological Data
### Length and Age Compositions
### Age Structures
### Ageing Precision and Bias
### Maturation and Fecundity
### Natural Mortality
### Sex Ratio
### Length-Weight Relationship
### Steepness

<!--chapter:end:north.Rmd-->


# Executive Summary{-}

Placeholder


## Stock{-}
## Landings{-}
## Data and Assessment{-}
## Stock Biomass{-}
## Recruitment{-}
## Exploitation Status{-}
## Reference Points{-}
## Management Performance{-}
## Unresolved Problems and Major Uncertainties{-}
## Decision Table{-}
## Research and Data Needs{-}
## Basic Information
## Life History
## Historical and Current Fishery Information
## Summary of Management History and Performance
## Foreign Fisheries

<!--chapter:end:south.Rmd-->

